### ISSUE TITLE
Document how well this handles latency in the alert and load test results?

### ISSUE THREAD

**Issue by jcrben** [Cyclenerd/poweroff-google-cloud-cap-billing#9]
When billing alerts from Google Cloud (or other services) are mentioned, there's usually the caveat around latency between the alert and shut down. For example https://cloud.google.com/billing/docs/how-to/notify#cap_disable_billing_to_stop_usage says this:

> Note: There is a delay between incurring costs and receiving budget notifications. Google Cloud products report usage and cost data to Cloud Billing processes at varying intervals, so you might incur additional costs for usage that hasn't arrived at the time that all services are stopped.
Following the steps in this capping example is not a guarantee that you will not spend more than your budget.
Recommendation: If you have a hard funds limit, set your maximum budget below your available funds to account for billing delays.

How well does this handle that issue? Have you tried stress testing it by running a quick lambda function or something and seeing how many invocations happen before the billing is cut?

I was reading on this a while back and saw this thread https://news.ycombinator.com/item?id=25376768 where someone said this:

> As a former victim to the same issue as OP, I am furious every time I see a Googler promote that as a solution.
In our case, we racked up a $10000 bill on BigQuery in ~6 hours, when a job was failing and auto-retrying. 
> 
> We had set up every alert correctly and our reaction time was about 5 minutes (about $100 of usage, no big deal). So how did we get a $5000 bill? 
> 
> Google's alert was 6 hours late (according to them, this was root-caused to us, because we were submitting jobs continuously). They pointed to their TOS and said they don't guarantee on-time delivery of the alert. I had to write up a blog post with fancy graphs and prepare it for social media before they finally agreed to eat the bill.

I saw the discussion at https://www.reddit.com/r/googlecloud/comments/va0cc0/automating_cost_control_by_capping_google_cloud/ but it didn't seem like anyone asked this question.

**Comment by Cyclenerd** [comment]
As described, each of the many Google services has its own delayes. Of course, there are services where you can generate a huge amount of costs in a very short time with one click. Example BigQuery. But you need a lot of data for this, which from experience is not the case in sandbox environments. If you feel unsure or want to further limit yourself or your users, you can also adjust quotas (https://github.com/Cyclenerd/terraform-google-quota-limits)... But, imo. the default for credit card accounts is actually quite good, so you don't spend too much. If you have further questions about the cost structure, please contact a Google Partner.
